# permissions for end users to edit springboots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: springboot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spring-boot-operator-demo
    app.kubernetes.io/part-of: spring-boot-operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: springboot-editor-role
rules:
- apiGroups:
  - spring.yujiangjun.github.com
  resources:
  - springboots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spring.yujiangjun.github.com
  resources:
  - springboots/status
  verbs:
  - get
